opcua/uatypes.py
If the name has a ':' in it then unpacking values fails, only split on
first.
=> Split on first ':' only.

opcua/uatypes.py
Specification says that strings are encoded as sequences of UTF-8
characters preceded by length in bytes. But the length was calculated
as a number of UTF-8 characters. So packing of strings with
non-ASCII characters was broken.
=> Fix string length in pack_string()

tests.py
This is a small test for a bug fixed in #13.
If you try to revert #13 and then run tests, you will get the following error:
```
======================================================================
FAIL: test_unicode_string_nodeid (__main__.Unit)
----------------------------------------------------------------------
Traceback (most recent call last):
File "tests.py", line 150, in test_unicode_string_nodeid
self.assertEqual(new_nid, nid)
AssertionError: NodeId(ns=1;s=hëll) != NodeId(ns=1;s=hëllò)
----------------------------------------------------------------------
```
Note that the last letter of the node name is lost due to wrong length in the binary packet.
=> Test for a bug in pack_string() (see pull request #13)

opcua/uatypes.py, tests.py
Add tests for all types of NodeId
=> Fix NodeId.to_binary() for ByteStrings

opcua/node.py, opcua/uatypes.py
The UaExpert is not happy with wrong type of data in AccessLevel and UserAccessLevel.
So the type should be explicitly set because of python types.
And one IMHO not needed comment is removed.
=> Explicit type for AccessLevel and UserAccessLevel

opcua/binary_client.py, opcua/binary_server_asyncio.py, opcua/node.py, opcua/uaprocessor.py, opcua/uatypes.py, opcua/utils.py
Fix some typos in messages. Set zero timestamp in BrowseParameters.View, because .Net UA servers show a strange behaviour when this timestamp is a current time.
=> Small fixes

opcua/address_space.py, opcua/internal_server.py, opcua/internal_subscription.py, opcua/node.py, opcua/subscription.py, opcua/tools.py, opcua/uaprotocol.py, opcua/uaprotocol_auto.py, opcua/uaprotocol_hand.py, opcua/uatypes.py, schemas/generate_model.py, schemas/generate_protocol_python.py, schemas/uaprotocol_auto_add.py, tests/tests.py
OK, this patch is really huge. The main idea here is to hide ExtensionObject conversions from user of this library.
All ExtensionObject members are now automatically converted to objects of correct type. Also, their default value is now None.
For example, now you can write:
```
if isinstance(params.UserIdentityToken, ua.UserNameIdentityToken):
print(params.UserIdentityToken.UserName)
```
instead of explicitly converting object:
```
id_token = ua.downcast_extobject(params.UserIdentityToken)
if id_token.TypeId == ua.FourByteNodeId(ua.ObjectIds.UserNameIdentityToken_Encoding_DefaultBinary):
print(id_token.UserName)
```
I removed downcast_extobject() and ExtensionObject class, they are no longer needed.
=> Clean up ExtensionObject handling

opcua/uatypes.py, tests/tests.py
Previously, datetime.utcfromtimestamp() was used,
which is limited to 1970-2038 range on 32-bit POSIX systems.
Adding timedelta to datetime(1601, 1, 1) works better.
=> Fix conversion from FILETIME to datetime

opcua/tools.py, opcua/uaprotocol_hand.py
Remove duplicate code in uatools.
Also, add default scheme opc.tcp:// if URL provided in arguments has no scheme.
=> Refactor command-line tools

opcua/xmlimporter.py, opcua/xmlparser.py
Extended the xml parser to cover the basic python data types.
Fixed a bug when the xml parser tried to import a null string.
Fixed a bug where the xml importer wouldn't assign ua node data type because the imported value was a zero.
=> XML importer updates

opcua/binary_client.py, opcua/uaprocessor.py, opcua/uaprotocol_hand.py, tests/tests.py
Client and server should respect BufferSize values and
should not send chunks bigger than peer's BufferSize.
Also, added base class for SecurityPolicy. Only None policy (no signing, no encryption) is implemented now, but I already have usable client-side security policies (tested on OPC foundation .net server), and I will push them after some more testing.
=> Split messages into MessageChunks

opcua/binary_client.py, opcua/client.py, opcua/security_policies.py, opcua/tools.py, opcua/uaprocessor.py, opcua/uaprotocol_hand.py, opcua/utils.py, tests/tests.py
Basic128Rsa15 and Basic256 are implemented.
Client now successfully connects to OPC foundation .net server with signing and encryption.
Dependency on cryptography module is completely optional: you
can use python-opcua without cryptography if you only use #None policy.
This pull request depends on #79.
I hope I didn't break anything :-)
=> Security policies implementation

opcua/address_space.py
if two thread using internal seesion to create moniter items and change data value concurently, MonitoredItemService.create_monitored_items & AddressSpace.set_attribute_value may deadlock.
test script:
```python
import sys
sys.path.insert(0, "..")
import logging
try:
from IPython import embed
except ImportError:
import code
def embed():
vars = globals()
vars.update(locals())
shell = code.InteractiveConsole(vars)
shell.interact()
from opcua import ua, uamethod, Server, Event, ObjectIds
class SubHandler(object):
"""
Subscription Handler. To receive events from server for a subscription
"""
def __init__(self):
self.counter = 0
def data_change(self, handle, node, val, attr):
self.counter += 1
return
print("Python: New data change event", handle, node, val, attr)
def event(self, handle, …
```
=> fix deadlock

opcua/binary_client.py, opcua/client.py, opcua/security_policies.py, opcua/tools.py, opcua/uacrypto.py
Clean up client's security policy API and move all crypto functions to uacrypto.
Added set_security() and set_security_string() methods to Client.
Removed duplicate server_certificate field, renamed
client_certificate and private_key to user_certificate and user_private_key.
=> Clean up client's security policy API

schemas/generate_address_space.py
Not closing the generated files may cause some errors when trying
to interpret the files in the same script later on (i.e. parsing errors due
to half written files).
=> Close generated address space files once the code generation is done

opcua/server/address_space.py
Hey,
I've tried to run the python-opcua server on a Raspberry-Pi.
Unfortunately starting the server and especially the construction of the address spaces takes quite a while (~57secs), so I started to play with the already built in caching of the address spaces.
To my surprise the loading performance was much worse when loading the the address space from a pickle file (~157secs).
However, simply working with the C-Implementation of the pickle mechanism and using the latest protocol version is delivering better results (cPython: ~33 secs / cPython + HIGHEST_PROTOCOL: ~22 secs).
I didn't do any exact performance tests so you shouldn't take those values too seriously :-)
However, since other persons report similar benchmark results (e.g. …
=> Improved loading performance when using cached address spaces

opcua/ua/uatypes.py
Fix #121: FILETIMEs after 31 Dec 9999 can't be converted to datetime.
=> Catch overflows in win_epoch_to_datetime()

opcua/common/subscription.py
Insert monitored item into map to avoid notification arrive before result return. This is the way how official .net opcua library handle async nature of the subscription.
=> fix race condition in subscription

opcua/server/binary_server_asyncio.py, opcua/server/internal_server.py
Please check if this is an acceptable solution for handling the transport objects. I tested it on my local system and it seems to work (with a single client). However it should be tested more. Especially because I am not sure if calling:
```python
self.iserver.asyncio_transports.remove(self.transport)
```
in connection_lost() is really going to remove the correct object.
=> Handle Asyncio Transports Explicitly

opcua/common/manage_nodes.py, opcua/common/node.py, opcua/server/address_space.py, tests/tests_common.py, tests/tests_server.py
Working on #161 I found out that inverse references are missing (from child to parent). So here is initial implementation. The result is cross-compared with server based on Unified Automation SDK and Textual specification (Part 3) is consulted. Following major changes are done:
* Hierarchical references are automatically added (parent <--> child)
* create_method now returns Node (as all other create methods (variable, object))
* create_folder is now merged with create_object since the difference is in only one variable
* On multiple places are written constants instead of hard-coded numeric values
* Tests for references are written and some others are extended
=> Added support for Inverse references

opcua/client/client.py
Allows using client as a context manager for the with statement:
```
with Client(URL) as client:
client.do_something()
```
=> Turn Client into a context manager

opcua/common/subscription.py
Classes involved:
- EventResult
- SubscriptionItemData
- DataChangeNotif
Unless you are doing some hack that requires old-style classes, they should be new-style ones to ensure forward compatibility.
=> New-style classes

examples/server-events.py, examples/server-example.py, opcua/__init__.py, opcua/common/event.py, opcua/common/manage_nodes.py, opcua/common/node.py, opcua/common/subscription.py, opcua/server/address_space.py, opcua/server/server.py, opcua/ua/__init__.py, opcua/ua/uaevents_auto.py, opcua/ua/uatypes.py, opcua/ua/uatypes_auto.py, tests/tests_common.py, tests/tests_server.py
Follwing the discussion in #133 and #159 I created new proposal, which is mix of original implementation and objects based implementation. @oroulet please give your opinion on following since I am starting to doubt on my object based idea (I generates additional code which is maybe not important at all. (This is just proposal so the test will probably not pass)
1. Object based proposal:
Object based proposal provides to freeze standard event types and better control over automatic filling of fields. We could implement an OPCUA-Object which takes care that every one of the UA objects (standard or custom) are provided into address space (something for #159).
@oroulet: Is this important in your opinion, does object based proposal provides some added value?
2. Generator-only based proposal: …
=> Events implementation proposal

opcua/server/address_space.py
When starting an opcua server, the creation of the address space is
currently a performance bottleneck. The startup process can be accelerated
by loading a pre-generated address space pickle.
However, the startup process still takes ~25 seconds on a raspberry pi
model b (compared to ~125 seconds when generating the address space from code).
Storing the address space in a shelve, where the data for each node is
pickeled individually, allows to further improve the startup performance
since only the nodes that are actually accessed are loaded from
disc (all other nodes are loaded later when they are accessed).
Since the default address space contains thousands of nodes but just a
small amount is actually accessed during startup, the startuptime could
be improved to ~3.5 seconds.
=> Perform lazy loading when restoring a cached address space

opcua/server/history.py, opcua/server/history_sql.py, tests/tests.py, tests/tests_history.py
The current implementation is actually a no-op since the data is truncated
correctly but not assigned back to self._datachanges.
Pop the first value instead since this function is called for every
datachange which means that not more than one value will every be removed
in a single call.
=> Correctly handle count parameter @ HistoryDict.save_node_value

examples/customobject.xml, examples/server-customobject.py, opcua/common/manage_nodes.py
The Node.add_object let you only create object of the type BaseObjectType. It would be nice if you also could create other types by providing an objecttype.
Like:
myobj = objects.add_object(idx, "MyCustomObject", myobjectype_nodeid)
The only thing this patch do is setting the correct NodeId in the TypeDefinition.
=> Support providing objecttype for the method add_object of Node

opcua/client/client.py
changed the function bytes to the function encode for python2 compatibility. Should take care of issue https://github.com/FreeOpcUa/python-opcua/issues/211
=> changed the function bytes to the function encode for python2 compatibility

examples/server-datavalue-history.py, examples/server-events-history.py, opcua/common/subscription.py, opcua/server/history.py, opcua/server/history_sql.py
Remove some event FIXMEs from subscription and make it match node.py.
Minor changes and cleanup to make history module consistent with events. Mainly that historizing new events now takes a list of event type nodes. The module which implements the history interface is responsible for formatting the events types itself (for example converting event types to a list of fields like in SQL)
I also cleaned up history examples and added a new example for historizing data changes on a variable, since at some point that example code was lost during all the events stuff.
=> Make History Consistent with Events

opcua/common/xmlparser.py, tests/custom_nodes.xml
The fragment below breaks then XmlImporter:
```xml
<UAVariable NodeId="i=30004" BrowseName="MyXMLVariableWithoutValue" DataType="String">
<References>
<Reference ReferenceType="HasTypeDefinition">i=69</Reference>
<Reference ReferenceType="Organizes" IsForward="false">i=30002</Reference>
</References>
</UAVariable>
```
The import doesn't break if an value element is present. According to the OPC UA schema it is allowed to don't have a value element ( see https://opcfoundation.org/UA/schemas/1.02/UANodeSet.xsd).
The error is due a small typo in XmlParser.__init__ :
```python
self.value = [] # should be None instead
```
The default value of a value is set to [], while at XmlImporter.add_variable it is checked to unequal to None:
```python
if obj.value is not None:
```
Set the default value …
=> xmlimport breaks when UAVariable doesn't have value element (2)

opcua/common/xmlimporter.py, tests/custom_nodes.xml
Support custom data types with the XmlImporter. The datatype can be base on:
- Type based on string version of nodeid
`<UAVariable DataType="ns=1;i=3004" ParentNodeId="ns=1;i=5002" NodeId="ns=1;i=6006" BrowseName="1:MyVar">`
- Type based on ua ojectids
`<UAVariable DataType="String" ParentNodeId="ns=1;i=5002" NodeId="ns=1;i=6006" BrowseName="1:MyVar">`
- Typed based on alias
`<UAVariable DataType="MyVarType" ParentNodeId="ns=1;i=5002" NodeId="ns=1;i=6006" BrowseName="1:MyVar">`
custom_nodes.xml is updated to let TestServer:test_xml_import verify the change.
=> Support xml address space import with custom data types

opcua/client/client.py, opcua/server/server.py, tests/tests_client.py, tests/tests_server.py
This seems to have been implemented without testing. As far as I can tell this never worked.
Context managers work the same way since Python 2.5 when they were introduced: https://docs.python.org/2.5/lib/typecontextmanager.html
=> fix __exit__ method of client and server class

opcua/common/xmlimporter.py, opcua/common/xmlparser.py, tests/custom_nodes.xml, tests/tests_server.py
Added loading of EnumValues ( listofextension oject ) to the xmlparser and xmlimport.
In combination with PR #238 python-opcua now fully supports importing Enumerations based on EnumString (ascending numbers) and EnumValues(numbers with gaps or bitmasks).
Example fragment ListOfExtensionObject of EnumValues:
```xml
<Value>
<uax:ListOfExtensionObject>
<uax:ExtensionObject>
<uax:TypeId>
<uax:Identifier>i=7616</uax:Identifier>
</uax:TypeId>
<uax:Body>
<uax:EnumValueType>
<uax:Value>1</uax:Value>
<uax:DisplayName>
<uax:Text>idle</uax:Text>
</uax:DisplayName>
<uax:Description/>
</uax:EnumValueType>
</uax:Body>
</uax:ExtensionObject>
<uax:ExtensionObject>
<uax:TypeId>
<uax:Identifier>i=7616</uax:Identifier>
</uax:TypeId>
<uax:Body>
<uax:EnumValueType>
<uax:Value>2</uax:Value>
<uax:DisplayName> …
```
=> [xmlimporter] support for values with EnumValues

tests/tests.py, tests/tests_crypto_connect.py
Instead of using our own solution for skipping test, we use
unittest.skip. This has the additional benefit that it works
with the automatic test discovery in Python >=3.2.
=> replace custom test disabling with unittest.skip

opcua/common/events.py, opcua/common/instantiate.py, opcua/common/ua_utils.py, tests/tests_common.py
If you create object type A and you derive a type B from it, then using the method `instantiate` will only create members of of type. 
This PR will use all parents, optional (reference HasModellingRule) elements are skipped.
CommonTests.test_instantiate_1 is also update to test and demonstrate the change.
=> support multiple depths of inheritance for instantiate

examples/server-xmlexporter.py, opcua/common/xmlexporter.py
This is for review. Only UAVariable method is partially done as an example.
Please give feedback on this design before I implement the remaining XML export methods.
FYI, I modeled the exporter after the importer, so a lot of junk from that is commented out. I left it there because the XML exporter basically has to reverse whatever the importer functions do so it makes it easier to write the methods.
=> Implement XML exporter

opcua/common/xmlparser.py
If node value is type Guid get the value from the child ```<string>``` tag.
Example XML to parse:
```xml
<UAVariable DataType="Guid" ParentNodeId="ns=1;s=Machine0" NodeId="ns=1;s=Machine0.Id" BrowseName="1:Id">
<DisplayName>Id</DisplayName>
<References>
<Reference ReferenceType="HasProperty" IsForward="false">ns=1;s=Machine0</Reference>
<Reference ReferenceType="HasTypeDefinition">i=68</Reference>
</References>
<Value>
<uax:Guid>
<uax:String>ead83ed2-7323-44ab-83ad-ed5d3be7bc2f</uax:String>
</uax:Guid>
```
=> Support importing Guid from XML

opcua/server/server.py
shortcut to linking python functions to UA Method nodes, for example
after instantiating an object from object type which has a method.
To be used after instantiating from a custom type which has a method node.
See: #297
=> Add link_method to server

opcua/common/manage_nodes.py
Only create an argument if needed (allowed by spec and cleaner than just having an argument node with empty array in Value)
Create argument properties in the same namespace as the parent method (needed for modeler, also makes more sense)
=> Improve method argument creation

opcua/server/internal_subscription.py
Fixed internal_subscription deadband_callback exception when old value are None.
See for more info #328
=> fixed internal_subscription deadband_callback exception 

opcua/common/xmlimporter.py, opcua/common/xmlparser.py, tests/custom_nodes.xml, tests/tests_unit.py, tests/tests_xml.py
First attempt to move namespace correction code out of xmlparser to xmlimport.
Part not finished sorting the nodes before import (_sort_nodes_by_parentid). This is a problem if the nodes not already are sorted in the xml file (default behavioral of UaModeler is sorted).
Please review and/or test.
=> Move nsrel to xmlimport

opcua/common/instantiate.py, opcua/common/ua_utils.py, opcua/common/xmlparser.py, tests/tests_common.py
Is there a way we can do something like this code?
Basically, if you have an ObjectType, and you instantiate from that type, but you want String Node Id (much more readable), the children will also have a string node id.
It looks like this:
And when you instantiate the new node with a String Node Id:
I feel like this will work fine because the parent node will always be unique, but perhaps if you have some strange structures this would break? Having children with the same browsename would also break this, but I think `instantiate` is already broken in this case because `if not ua_utils.is_child_present(node, c_rdesc.BrowseName)` is already searching via browsename.
(the primary reason I want this is for Modeler)
=> Improve instantiate when parent has string node id + small fixes

opcua/common/xmlexporter.py
Can't check `not val` because variable nodes with a value of 0.0 don't get exported, for example. Only Null Variants should be exported with an empty `<Value>` tag.
=> Exporter fix to allow exporting values of 0

opcua/common/ua_utils.py, opcua/server/server.py, tests/tests_server.py
Default the `server.export_xml` requires a node list for export.  An alternative `server. export_xml_by_ns` export default all nodes (except from namespace 0). Also you can be more selective by provide a list of ns indexes or uris of the nodes that should be exported.
Examples:
```python
server. export_xml_by_ns export('all.xml') # export all nodes (excepts ns=0)
server. export_xml_by_ns export('all.xml', 4) # export only nodes in ns=4
server. export_xml_by_ns export('all.xml', [3,4]) # export only nodes in ns=3 and 4
server. export_xml_by_ns export('all.xml', ['myspace.org','myspaceto.org']) 
```
Helper method `get_nodes_of_namespace` for getting the nodes of a certain namespace is added to `ua_utils`
=> export to xml based on namespaces

examples/server-datavalue-history.py, examples/server-events-history.py, opcua/server/address_space.py, opcua/server/internal_server.py, opcua/server/server.py, tests/tests_history.py, tests/tests_server.py
Bring back dump and load to do their original function and add methods for caching.
These serve different purposes.
load and dump: just dump the entire address space to binary and then reload it
cache: tries to speed up loading default address space, it doesn't support saving custom nodes and has other drawbacks; for example you can't delete nodes if using the cache
Also added `isession.close()` to the server stop code. This ensures all clean up is done, including the deletion of internal subscriptions (required for dumping address space)
=> Caching fixes

opcua/client/client.py
I have switched the values for `RequestedLifetimeCount `and `RequestedMaxKeepAliveCount`, because on an idle connection (no changes of the monitored items) the server will wait for `KeepAliveCount*PublishingInterval` and then send an empty message to the client. This empty message will trigger a PublishRequests. Buf if `LifeTimeCount` is smaller than `KeepAliveCount`, the server will close the subscription before sending the empty message.
Also added the values as `kwargs` to create_subscription.
> KeepAliveCount
If there is no data to send after the next PublishingInterval, the server will skip it. But KeepAlive defines how many intervals may be skipped, before an empty notification is sent anyway: to give the client a hint that the subscription is still alive in the server and that …
=> Changed values for RequestedLifetimeCount and RequestedMaxKeepAliveCount

opcua/common/callback.py, opcua/common/copy_node.py, opcua/common/ua_utils.py, opcua/tools.py, opcua/ua/ua_binary.py, schemas/generate_address_space.py, tests/tests_client.py, tests/tests_cmd_lines.py, tests/tests_crypto_connect.py, tests/tests_history.py, tests/tests_server.py, tests/tests_xml.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Prefer `format()` over string interpolation operator](https://www.quantifiedcode.com/app/issue_class/4ACGxFj1)
Issue details: [https://www.quantifiedcode.com/app/project/gh:FreeOpcUa:python-opcua?groups=code_patterns/%3A4ACGxFj1](https://www.quantifiedcode.com/app/project/gh:FreeOpcUa:python-opcua?groups=code_patterns/%3A4ACGxFj1)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality …
=> Fix "Prefer `format()` over string interpolation operator" issue

.travis.yml, opcua/common/ua_utils.py, opcua/common/xmlimporter.py, opcua/common/xmlparser.py, opcua/server/address_space.py, setup.py, tests/tests_xml.py
Allows to parse ListOfDateTime values and seems to correct a typo for Bytes.
--
More details in issue #377 
By the way, XML with "Byte" and "SByte" gives me warning of non implemented types, however they are mentioned in documentation from OPC Fondation while "Bytes" is not. 
Is that a macro-type for both?
=> Removed duplicate code from XML parser

opcua/server/internal_subscription.py
Client can set a deadband filter to several types (Part 4 7.16.2). Currently this mode isn't checked.
This pr makes the check of those types explicit.
Also some errors can be prevent by this, for example when string type provides a filter with type None. The current situation results in some math checks with strings, which results in an exception.
=> Improve deadband handling, skip if deadbandtype is none.

opcua/common/xmlexporter.py
Improve compatibility with:
* https://opcfoundation.org/UA/2011/03/UANodeSet.xsd
* https://opcfoundation.org/UA/2008/02/Types.xsd
Impove this compatibility make it possible to read the information models into other tools like UaModeler.
Mostly fixes to garantee the order of the elements according the xsd:
* NamespaceUris: Make sure that the namespacuris are on top (above the aliases)
* UAVariable: Place the values below the references
* uax:Boolean:  values should be 'true' and 'false' (lower case)
* Argument: place the members in the correct order
Btw correct format of the xml file can be checked with XML validator against the XSD.
=> xmlexport improve compat with xml schema

opcua/common/xmlparser.py, tests/tests_xml.py
In the xsd https://opcfoundation.org/UA/2008/02/Types.xsd the Value uax element allpws nillable like:
```xml
<Value><uax:String></uax:String></Value>
```
Without this fix an exception will be thrown that the string object is `None` in `uautils.string_to_val`.
Test included.
=> [xmlimport] support nillable values

opcua/common/xmlparser.py, tests/tests_xml.py
Python3 is failing to import bytestring objects due to calling replace method after encoding the imported string into utf8.
This works with python2 but not python3 as reffered in issue #377
=> Importing bytesting objects from XML in Python3

opcua/common/xmlimporter.py
This fixes the error when importing an xml file with aliases used in objects.
self.make_objects() uses self.to_nodeid() which can now take the defined aliases into account.
=> Load Aliases before make_objects()

opcua/common/ua_utils.py, tests/tests_xml.py
The xml import for the type Byte is broken, fixed ua_utils.string_to_val for Byte and SByte.
Step to reproduce:
- Add  xml_test_byte to the xml test suite
**Backgound:**
The current implementation treat Byte as single byte version of a ByteString, but Byte is just a nummeric value limited to 255 values. The same story for SByte.
In the https://opcfoundation.org/UA/2008/02/Types.xsd the definition is:
```xml
<xs:element name="Byte" nillable="true" type="xs:unsignedByte" />
```
Where ByteString is:
```xml
<xs:element name="ByteString" nillable="true" type="xs:base64Binary" />
```  
`xs:unsignedByte` is just a nummreic value without encoding, see for more info https://www.w3schools.com/xml/schema_dtypes_numeric.asp.
=> [xmil_import] Fixed (S)Byte string_to_val

.gitignore, tests/tests_xml.py
Ignore .xml files generated by the tests. The files are renamed to have prefix _tmp_tests__ and ignore them.
=> Ignore file proposal

opcua/server/address_space.py
`make_aspace_shelf` fails with `TypeError: 'NodeId' object is not iterable`
=> iterate over items in make_aspace_shelf

opcua/ua/uatypes.py, tests/tests_common.py
Based on discussion in #426:
Support correct VariantType for node.set_value in case of an IntEnum.
=> support IntEnum with Variant guess type

opcua/server/event_generator.py, opcua/server/internal_server.py, tests/tests_server.py
I noticed in UaExpert that the attribute EventNotifier always gets the values SubscribeToEvents and HistoryRead.
Creating an event source with the call get_event_generator, the attribute EventNotifier is always set with SubscribeToEvents and HistoryRead. Probably HistoryRead must only be set after calling iserver.enable_history_event() to enable the history keeping for events.
=> Only add HistoryRead after event history is enabled

opcua/server/standard_address_space/standard_address_space_part11.py, opcua/server/standard_address_space/standard_address_space_part3.py, opcua/server/standard_address_space/standard_address_space_part4.py, opcua/server/standard_address_space/standard_address_space_part5.py, opcua/server/standard_address_space/standard_address_space_part8.py, opcua/server/standard_address_space/standard_address_space_part9.py, schemas/generate_address_space.py, tests/tests_client.py, tests/tests_common.py
Fixed as crash for list of localized strings (see #426).
Old implemenation generated something like:
```python
attrs.Value = ua.Variant(['Server', 'Client', 'ClientAndServer', 'DiscoveryServer'], ua.VariantType.LocalizedText)
```
Due a change in the Variant implemention this cause an exception on to_binary. New implementation generates:
```python
attrs.Value = [ua.LocalizedText("Server"),ua.LocalizedText("Client"),ua.LocalizedText("ClientAndServer"),ua.LocalizedText("DiscoveryServer")]
```
=> Fix codegeneration list of localized text

opcua/server/address_space.py, opcua/server/binary_server_asyncio.py, opcua/server/server.py, tests/tests.py, tests/tests_server.py
Created two fixes:
Starting the server failed when for eg a socket was already is use. The interval server was already started and caused the application to 'hang'. Fixed by stopping the internal server on an exception while starting the binary server. 
Noticed an exception on the server after an unsubscribe for data changes (by UaExpert)  on a node already deleted by the server. Added a check in delete_datachange_callback to prevent the KeyError exception.
=> Stop server on start failure and prevent exception

examples/server-ua-python-mirror.py
Please review this example and let me know if it is clear and worth adding to our collection. I found it very useful in my personal projects and would like to expand it.
Do not merge because I didn't test it yet.
Ultimate goal would be to generate python objects that subclass `UaObject` from UA Modeler for fast application development.
=> Add ua to python mirroring example

opcua/common/xmlimporter.py, opcua/ua/uatypes.py
Since sometime python-opcua supports registering custom classes for encoding/decoding custom extension object (Se PR #388). Only till know this was not supported by xmlimport.
=> [xmlimporter] support use of extension dictionaries

opcua/client/client.py
When TimeoutError is thrown during the call to disconnect, the socket remains open. This will case the appliation to deadlock
This will address issue https://github.com/FreeOpcUa/python-opcua/issues/453
=> close socket even when timeout occurs

setup.py, stdeb.cfg
Hello
I changed the name option in setup.py to opcua (instead of freeopcua), so that the generated debian package filename will be python3-opcua.
Without this patch the package installation for python3-opcua-widgets fails (requesting python3-opcua to be installed).
Moreover, this is more in accordance with opcua-client and opcua-widgets packages naming.
Is this fine or must the package be called freeopcua?
Cedric
=> Corrections for generating debian packages

opcua/server/uaprocessor.py
According to OPC Unified Architecture Specification (Part 4: Services,
7.28 RequestHeader) a TimeoutHint value of 0 shall be treated as no timeout:
"The value of 0 indicates no timeout.".
This fixes issues with OPC UA clients never receiving any PublishResponse
if a TimeoutHint of 0 was used in the according PublishRequest.
=> treat TimeoutHint=0 as mandated by OPC Unified Architecture Specification

opcua/server/standard_address_space/standard_address_space.py, opcua/server/standard_address_space/standard_address_space_part10.py, opcua/server/standard_address_space/standard_address_space_part11.py, opcua/server/standard_address_space/standard_address_space_part13.py, opcua/server/standard_address_space/standard_address_space_part3.py, opcua/server/standard_address_space/standard_address_space_part4.py, opcua/server/standard_address_space/standard_address_space_part5.py, opcua/server/standard_address_space/standard_address_space_part8.py, opcua/server/standard_address_space/standard_address_space_part9.py, tests/tests.py, tests/tests_standard_address_space.py
I forgot to generate the standard address space after the the latest patches in #509 
This PR contains the update and a test for references in standard address space.
closes #508
=> Update standard address space

opcua/common/instantiate.py, opcua/common/node.py, tests/tests_common.py
From the OPC-UA specification Part 3 (6.2.2)
> If no ModellingRule exists then the Node is neither considered for instantiation of a type nor for
subtyping.
This PR implements this behavior.
Tool-generated nodesets should already contain the appoproriate modelling rules.
I have patched the `Node` API to add them for types' children as well (with opt-out).
=> Don't instantiate nodes without a modelling rule

opcua/client/client.py, opcua/client/ua_client.py, opcua/ua/uaprotocol_hand.py
Solves the issue #492. Now it is possible to set MaxMessageSize and MaxChunkCount via properties. Servers that don't accept 0 can be connected now when the new properties are used with proper values before establishing a connection to a server  (in my case I used `client.set_max_messagesize(65536)`). 
**Important:** Currently only `client.send_hello` makes usage of the new introduced properties. It needs to be checked if other operations also should make usage of this (properties) for consistency reasons.
=> Added properties to configure MaxMessageSize and MaxChunkCount

opcua/common/methods.py, opcua/server/address_space.py, tests/tests_common.py
This PR patches the method call system to handle `ua.StatusCode` and `ua.CallMethodResult` properly.
So the callback can indicate errors or invalid arguments.
=> allow passing specific method results

opcua/common/xmlimporter.py
The first commit fixes an issue with extension objects, as the datatype nodeid was not migrated.
The second commit enforces namespace migration in all XMLImporter.to_nodeid uses.
=> Expand namespace migration in XMLImporter

opcua/client/client.py, opcua/common/structures.py, opcua/server/binary_server_asyncio.py, opcua/server/history.py, opcua/server/server.py, opcua/server/uaprocessor.py
In various places in the library, there were some print()s. These make it hard to control the output of the library externally, e.g. when supressing logging output for clean testing-logs.
This commit attempts to replace all leftover print()s by logging calls.
=> Replace leftover prints with logging

opcua/server/server.py, opcua/ua/ua_binary.py
If methods are used with custom data types, which contain strings, UAExpert encodes these as `CharArray`.
However, the current struct handling packs/unpacks only Variant types, which cover only a subset of the standard types for binary encoding.
This PR considers the Primitives types as well; Variant types take precedence.
In addition the server now exposes `load_type_definitions` (same as for the client) that can be called to setup extention object class automatically at server-side.
Without this fix the `CharArray` is handled as a structure and the methods call will never get a response due to an exception in between.
=> Fix handling of CharArray in Structs

opcua/common/subscription.py
This allows client to set the size of the queue. Some servers does not respect size of 0 (which should be unlimited if I understand the specs correctly).
=> subscribe_events should allow to specify queue size

README.md, opcua/server/server.py, opcua/server/uaprocessor.py
Very minor change to fix three mis-spellings of "session", twice in log statements and once in a docstring.
Just to be paranoid, I wanted to run tests after these changes, and found that the Readme instructions for runnings tests are outdated. Hence, I changed those too.
=> fix typo: “sesssion”

examples/client-minimal.py
I tried the example together with the `server-minimal.py`. The origin browse path inside the `client-minimal.py `was not correct and so the client always stopped with an error. With the given pull request, the client works without any problems.
=> Fixed wrong browse path

opcua/client/client.py
Under certain conditions, normally when the server is under heavy load, it may fail creating session, if this happens we need to close the socket.
=> During call to connect, disconnect socket when create_session fails

opcua/client/client.py
Password needs to be encoded as utf-8, otherwise binary serialization
will fail with:
~/venv/lib/python3.6/site-packages/opcua/client/client.py in connect(self)
258             self.disconnect_socket() # clean up open socket
259             raise
--> 260         self.activate_session(username=self._username, password=self._password, certificate=self.user_certificate)
261
262     def disconnect(self):
~/venv/lib/python3.6/site-packages/opcua/client/client.py in activate_session(self, username, password, certificate)
432         else:
433             self._add_user_auth(params, username, password)
--> 434         return self.uaclient.activate_session(params)
435
436     def _add_anonymous_auth(self, params):
~/venv/lib/python3.6/site-packages/opcua/client/ua_client.py in …
=> Fix password authentication using SecurityPolicy#None

opcua/client/client.py, opcua/common/xmlimporter.py, opcua/common/xmlparser.py, opcua/server/server.py, tests/tests_xml.py
Introduce an optional parameter xmlstring throughout the import_xml
chain (client, server, xmlimporter, xmlparser) to allow specifying
a XML string instead of a path.
If both are given the string takes precendence.
=> Allow importing XML from string

opcua/client/client.py, opcua/client/ua_client.py, setup.cfg
The README says:
> Code follows PEP8 apart for line lengths which should be max 120 characters and OPC UA structures that keep camel case from XML definition.
But that's not actually true :)
This PR does two things:
* Address all but one of warnings and errors found by `flake8` in the `opcua/client` directory. Why only that directory? I had to start somewhere. Why "all but one"? Because the remaining one will be fixed once the accompanying `FIXME` comment is addressed.
* Add a `setup.cfg` file that captures the flags that make `flake8` behave the way the README file suggests we want a style checker to behave in this repo (ignore auto-generated files, line length of 120). You can now run the command `pip install flake8 && flake8 opcua` and get a list of PEP8 violations that are actually …
=> PEP-8 fixes for opcua/client/*.py files

opcua/client/client.py, opcua/client/ua_client.py, tests/tests_client.py
Fixes #599 
In addition to the example shown there, I noticed that the same applies to the keepalive thread in `opcua.client.Client` where I added a `join()` too.
=> join() background threads in client after stopping them

opcua/server/internal_server.py, opcua/server/subscription_service.py, opcua/server/uaprocessor.py
cfr. https://github.com/FreeOpcUa/python-opcua/issues/612
Note: requested parameters are shamelessly ignored and the original subscription settings are sent back to the OPC-UA client.
=> Subscription Service: ModifySubscriptionRequest

opcua/server/standard_address_space/standard_address_space_part9.py, schemas/generate_address_space.py
> [RFC] This attempt to fix #617 . I didn’t re-generate the address-space code yet, but simply wanted to show the change of the code-generator itself ….
Address-space code-generation didn’t handle nodes with LocalizedText in
Value-Attributes correctly before: It generated non-serializible
Attributes.
This fix redeems this so that proper LocalizedText objects are used,
which can be cleanly serialized.
=> Handle LocalizedText-Values in code generation

opcua/crypto/uacrypto.py
This commit will fix the deprecation warning about the signer and verifier.
=> fix 'CryptographyDeprecationWarning: signer and verifier have been deprecated.'

opcua/common/utils.py
Since Python 3.4.4, `asyncio.async()` has been a deprecated alias to `asyncio.ensure_future()` and in Python 3.7 the`asyncio.async()` alias was removed.
=> Updates asyncio to work with Python 3.7

opcua/server/binary_server_asyncio.py, opcua/server/internal_server.py, opcua/server/server.py, opcua/server/subscription_service.py
Sorry this is a new PR — for some reason GitHub greyed out the »reopen« button on the old PR.
The various Server objects use a utils.ThreadLoop to handle the
asyncio-mainloop. This Thread(~like) object is not getting
re-initialized in a start()⇒stop()⇒start()-scenario, which leads to a
»Threads may only be started once« exception.
To fix this, we dump the old ThreadLoop object upon re-initialization,
and hand the new object around.
=> Fix re-initialization of ThreadLoop in InternalServer

opcua/common/xmlimporter.py, opcua/common/xmlparser.py, opcua/server/address_space.py
This reverts 0b6c4d8, because it overwrites the parent for all backward references.
> parent giving as ParentNodeId misses the ref type, so better to prioritize the ref descr
if ParentNodeId is given, I would expect a corresponding backward reference.
I have added a warning if this is not the case. In addtion the parent will be deleted.
As an alternative this special case could be handled later by searching for a corresponding forward reference from the parent..
=> Fix reference and parent parsing

opcua/client/client.py, opcua/client/ua_client.py
https://github.com/FreeOpcUa/python-opcua/issues/664
I took the liberty to throw a more relevant ConnectionError instead of TimeoutError in the open_secure_channel() method. Another option is an ua.UaError derived type?
=> fixes TimeoutError in KeepAlive thread

opcua/server/internal_subscription.py
From Part 4 (1.03), 5.12.1.2 
> The Server may support data that is collected based on a sampling model or generated based on
an exception-based model. The fastest supported sampling interval may be equal to 0, which
indicates that the data item is exception-based rather than being sampled at some period.
=> implement support for subscription publishing interval 0

opcua/common/manage_nodes.py, tests/tests_common.py
Fixes #694 
Before it only deleted the first level of nodes below the specified
list, which was not what the parameter `recursive` conveyed to the user.
This also adds a test, which failed in current master, but succeeds in this branch.
=> Make recursive node deletion truly recursive

opcua/server/address_space.py
All other places use UInt32 for NodeClass. Make sure this is consistent.
=> Make sure NodeClass attribute is of type UInt32

opcua/common/subscription.py
NotificationData is sometimes None. And that causes an exception that breaks
the flow and no SubscriptionAcknowledgement is created and published
to the server.
=> Added check for None on NotificationData

opcua/server/address_space.py
Deleting a node on which any client holds a datachange-notification
subscription, NodeManagementService._delete_node_callbacks fails because
the size of the dictionary it loops over changes. Here, we solve this by
not using the .items() iterator, but making a copy in form of a list
first ….
This is related, but not the same as #659 — their problems was calling from within an existing callback path — here the call legally originates from a separate callpath.
=> Delete datachange_callbacks only on copy of dict to delete them from

opcua/client/ua_client.py
Gracefully handle a client.disconnect() when the underlying socket is already closed.
cfr. https://github.com/FreeOpcUa/python-opcua/issues/741
=> fix OSError: [Errno 9] Bad file descriptor

opcua/ua/uatypes.py
to_binary() was replaced by variant_to_binary as of commit e1067bac
https://github.com/FreeOpcUa/python-opcua/blob/9c115cd4b6a673037e5a1766c2457d1fed1241bf/opcua/ua/uatypes.py#L759-L761
* to_binary() was removed from all classes in uatypes.py except for this one. Probably leftover during refactoring. No leftovers in the source that rely on this method.
* Additionally, it uses an ugly import inside...
Unit-tests also ok.
=> removed deprecated to_binary() from Variant

opcua/client/ua_client.py
EBADF [errno 9]: socket connection is closed.
ENOTCONN [errno 107]: socket never connected.
cfr. https://www.gnu.org/software/libc/manual/html_node/Receiving-Data.html
=> fix client.disconnect() OSError: [Errno 9/107] EBADF/ENOTCONN

opcua/common/connection.py
See https://github.com/FreeOpcUa/python-opcua/issues/745
=> fix: set SecureConnection state to 'open' on OpenSecureChannelResponse

opcua/ua/uatypes.py
See https://github.com/FreeOpcUa/python-opcua/issues/755
This fixes inconsistent Encoding types when performing
y=variant_to_binary(x) -> x2=variant_from_binary(y) on
auto-generated attributes in the standard address space.
=> fix: Setting LocalizedText.Text attribute does not update Encoding

.gitignore, opcua/client/client.py, opcua/client/ua_client.py, opcua/common/connection.py
I was having an issue catching OPC UA server error responses when trying to create an OPC UA client because the `UaStatusCodeError` would be logged in the socket thread and a `concurrent.futures.TimeoutError` would get thrown in the main process. By re-raising the `UaStatusCodeError`, the main process can catch it and provide more details as to why the client connection can not be established.
**Server:** Instance of Prosys OPC UA Simulation Server in a Docker container. Set the Server Name to `pika`.
**Client code:**
```python
import concurrent.futures
import logging
import opcua
from opcua.ua import status_codes
from opcua.ua.uaerrors import UaStatusCodeError
logging.basicConfig(
level=logging.INFO,
format="%(asctime)s.%(msecs)03d [%(name)s] %(thread)d %(levelname)s - %(message)s", …
```
=> Surface send_hello server errors

opcua/common/xmlimporter.py
Good Day developers, thank you again for your work!
Story:
I wanted to import an ObjectType and Object of this object type from XML 
and the issue was, that after server starts and import, an Object hast to references for "HasTypeDifinition", one of them pointing to wrong NodeID. 
Long story short -- I was able to fix it and it seems like it was a typo:
In a previous code, the `_migrate_ns `function was called twice on reference_type: once in `make_objects `and once in `_get_node`. I fixed got rid of mitigation in `make_objects`, because I think originally developer wanted to call the privat `_to_nodeid ` method.
P.S. I'm not sure if parent link requires similar changes, because I don't know how to check it
=> Hope to fix an import of type_definitions, and parentlink.

opcua/common/manage_nodes.py
Hi again, thank you developers for your work.
Issue: while creating object via `Node.add_object()`, the resulting object has either: Namespace index in DisplayName or Default Namespace 0 in BrowseName. I fixed it and checked functionality:
with the new version user can supply `bname` attribute to `Node.add_object()` as `QualifiedName`, as `QualifiedName.to_string()` and simple string and all versions worked properly.
Nevertheless, I'm not sure if my test are sufficient.
=> Fix object creation

examples/server-enum.py
In order to make the custom Enumeration work, it is needed that the `EnumString` is a property of the Enum data type. I got this by looking at the built-in server enumeration `ServerState`, where it the same case.
After this change, even UaExpert let me choose the enum from a drop-down list.
Also in the `ServerSate` datatype, there is a reference of `ModellingRule` set to `Mandatory`. I don't know if this is actually "mandatory" for the full functionality of the custom enumeration, but if so, add the additional line to create the reference:
```python
es.set_modelling_rule(ua.ObjectIds.ModellingRule_Mandatory)
```
Best regards,
testunde
=> Set EnumStrings as property of custom enumeration datatype

opcua/server/registration_service.py, opcua/server/server.py, tests/tests_common.py, tests/tests_server.py
If I want to register my server to a discovery server, I get the following error:
```
Traceback (most recent call last):
File "testServer.py", line 112, in <module>
register.register_to_discovery(serverToRegister=server, discoveryUrl="opc.tcp://localhost:52010/discovery/")
File "/usr/lib/python3.7/site-packages/opcua/server/registration_service.py", line 56, in register_to_discovery
self._renew_registration(serverToRegister, registrationClient, period=period)
File "/usr/lib/python3.7/site-packages/opcua/server/registration_service.py", line 80, in _renew_registration
self._register_server(serverToRegister, registrationClient)
File "/usr/lib/python3.7/site-packages/opcua/server/registration_service.py", line 113, in _register_server
uaRegSrv.ServerUri = serverToRegister.application_uri …
```
=> Fix Server-field access for server registration at discovery server

opcua/client/ua_client.py, opcua/common/subscription.py, opcua/server/internal_server.py, tests/tests.py, tests/tests_subscriptions.py
Due to how Futures are used, we could timeout on the client side, but
still sucessfully create a subscription and add callbacks in the
_receiver thread. Once this happens, receiver thread will deadlock on
receiving the publish response from the server due to a while loop that
waits for the subscription_id to be set. This will never happen as it
was supposed to be set in the main thread, which timed out and failed.
The fix is to make sure we set the subscription_id in the _receiver
thread as a separate callback. This is not the ideal fix, which would
probably include re-designing the Subscription class API in a way to
allow checking for the staus, and changing the way
Client.create_subscription works. Since we don't want to make large
changes to this - let's just go with a simple fix that …
=> [subscriptions] Fix race condition in client when creating subs

opcua/server/internal_server.py
Some client systems, such as KepWare-Server, query the OperationLimits
and adapt their behavior accordingly. Unfortunately, if the
OperationLimits are missing, connecting will fail.
To redeem these cases, let’s set liberal but managable
OperationLimit-defaults.
closes #815
=> Set OperationLimits values correctly

opcua/ua/uatypes.py, tests/tests_unit.py
Otherwise StatusCode objects will carry a wrong name and doc after
deserialization.
Also add a test for proper resolution of name/doc from value.
=> Convert StatusCode value to name and doc on-the-fly

opcua/server/uaprocessor.py
According to the OPC UA specification V1.04 part 4, the server response to an unsupported service should be a ServiceFault with the service result code **Bad_ServiceUnsupported** and not the currently implemented operation level result code **Bad_NotImplemented**. (see OPC UA specification part 4, chapter 7.34.2, page 151)
This implementation is causing a hang during reconnection with B&R AsOpcUac OPC UA client library because the library does not expect an operation level result code for the service result.
Other servers i have seen (for example Unified Automation) also respond with Bad_ServiceUnsupported to unsupported services.
=> [Server] Fix bad ServiceResult for unsupported services

opcua/crypto/security_policies.py, opcua/server/uaprocessor.py, opcua/ua/uaprotocol_hand.py
Previously this was hardcoded to sha1. Fix this by introducing a
new URI field in the SecurityPolicy classes carrying the correct
URIs.
This fixes complaints by some UA clients that match requested
security profiles against the server response and warn the user.
=> Use correct signature algorithm in create session response

opcua/common/event_objects.py, opcua/server/event_generator.py
Before, the localtime field was set to a wrong datatype (DateTime
instead of TimeZoneDataType), and didn’t contain the local timezone
offset, but the current localtime.
=> Fix localtime field of events

opcua/server/internal_subscription.py
There were two major issues. First, _eval_el was called instead of _eval_op in recursive
calls, which would always fail.
Secondly, there was a misplaced line of code in "and" evaluation in _eval_el, which would
cause it to always fail.
=> Fix WhereClauseEvauluator

opcua/common/events.py, opcua/server/history.py, opcua/server/history_sql.py
History uses the emitting node to group events, but both implementations incorrectly used event.SourceNode to sort events. This changes that, and also makes it so that the emitting_node on events always is a NodeId, which was sometimes not the case before.
Resolves #896
=> Fix historizing events with specified SourceNode

opcua/ua/uatypes.py, tests/tests_unit.py
Thank you for taking the time to review my PR!
* When guessing the type of a list, look at the type of every element, not just the first one.
* Raise an error if there are multiple types, unless the types are `int` and `float`.
* Lists of `int` and `float` are treated as `float`.
* Tests for the above.
While working with some device drivers, I was seeing errors with long stack traces and the message:
struct.error: required argument is not an integer
This was caused by writing lists of coordinates in which not every element has decimal precision. I found it perplexing that I wouldn't see the error with:
[-110.1,0,64.25,180,0,180]
but would with:
[-110,0,64.25,180,0,180]
This is converting `[1, 2.0, 3]` to `[1.0, 2.0, 3.0]` with just a `debug` to show for it. That kind of conversion already …
=> Handle lists of multiple types in ua.Variant._guess_type

opcua/server/server.py, tests/tests_server.py
The `create_custom_data_type` method of the `opcua.Server` creates a node with class node "ObjectType", which is incorrect. This PR fixes this issue.
=> Fix custom data type creation

opcua/server/uaprocessor.py
Allows `python-opcua` to be used with [OPC Publisher Edge Module](https://github.com/Azure/Industrial-IoT/blob/master/docs/modules/publisher.md) by stubbing `SetPublishingMode` and `SetMonitoringMode`:
NOTE: This pull request does **not** implement `SetMonitoringMode`, nor `SetPublishingMode` functionality.
Related issue:
[WARNING:opcua.server.uaprocessor:Unknown message received FourByteNodeId(i=769)](https://github.com/FreeOpcUa/python-opcua/issues/594)
=> Opc publisher support

opcua/common/utils.py, opcua/server/internal_server.py
Stopping the InternalServer object should be a synchrounous call (once
the call returns the caller can be sure that the server if fully
stopped).
Hence, instead of just pushing a stop callback into the ThreadLoop wait
for the ThreadLoop to finish before returning.
Also re-order the shutdown to match the setup code.
=> Properly shut down ThreadLoop

opcua/server/internal_server.py
According to OPC Unified Architecture, Part 5, 6.3.11
OperationLimitsType all Max* properties shall have datatype
UInt32.
Fix this by explicitly setting the variant type to UInt32
instead of defaulting to Int64.
This fixes connectivity issues with the KepwareServerEx OPC-UA client.
Introduced in 21432df9fb02bbd3e45d7fe2b4023d76db94738f
=> Fix OperationLimits data type to UInt32

opcua/server/address_space.py
https://github.com/FreeOpcUa/python-opcua/blob/4af9cda09afee5fb636ab6e43df1f588e88becbc/opcua/server/address_space.py#L96
vs.
https://github.com/FreeOpcUa/python-opcua/blob/d9a9f42ddf17f4fc89e9aed8350c9d4046f3f986/opcua/server/address_space.py#L134-L141
desc -> direction
=> readability: parameter is direction i.o. BrowseDescription

opcua/server/internal_server.py, opcua/server/uaprocessor.py
Seems to be deprecated since 5108cf7939
=> cleanup: removed unused parameter 'external'

opcua/server/internal_subscription.py
During creating of a monitored item, the itemId counter is incremented twice:
Here:
https://github.com/FreeOpcUa/python-opcua/blob/bcb3e2d5966611f1efce3f179963147792a7fcd7/opcua/server/internal_subscription.py#L99-L102
and here:
https://github.com/FreeOpcUa/python-opcua/blob/bcb3e2d5966611f1efce3f179963147792a7fcd7/opcua/server/internal_subscription.py#L104-L110
Fix: Only increment when `result.MonitoredItemId` is assigned to `MonitoredItemCreateResult`
=> fix: itemId counter incremented twice

opcua/client/client.py, opcua/common/subscription.py
A method to reconciliate the client monitored_items with its server counterpart.
OPC-UA part 4 5.12.2.1 defines:
> If a Client called CreateMonitoredItems during the network interruption and the call succeeded in the Server but did not return to the Client, then the Client does not know if the call succeeded. The Client may receive data changes for these monitored items but is not able to remove them since it does not know the Server handle for each monitored item. There is also no way for the Client to detect if the create succeeded. To delete and recreate the Subscription is also not an option since there may be several monitored items operating normally that should not be interrupted. To resolve this situation, the Server Object provides a Method GetMonitoredItems that returns the list …
=> Subscription: Method to reconciliate MonitoredItems

opcua/client/client.py, opcua/common/subscription.py, tests/tests_client.py, tests/tests_subscriptions.py
Add unit test for the client / subscription reconciliate methods.
Also fix some nits raised here: https://github.com/FreeOpcUa/python-opcua/commit/de6a5185bcec893136d6e493b87753779657eea2#commitcomment-37372079
=> [Reconciliate MI] Add tests and fix nits

opcua/common/instantiate.py, opcua/ua/uatypes.py
cfr. https://github.com/FreeOpcUa/python-opcua/issues/822
`ua.NodeId(namespaceidx=res.AddedNodeId.NamespaceIndex)` defaults to` NodeIdType == TwoByteNodeId`. However, `TwoByteNodeId` does not encode the namespaceindex when serializing to binary. As a result, clients requests with null-identifier and nsidx != 0 (e.g. during instantiation of object types) will be decoded with nsidx=0 at server side.
https://reference.opcfoundation.org/v104/Core/docs/Part6/5.2.2/#Table8
=> bugfix: TwoByteNodeId does not encode namespace index

opcua/common/structures.py
If file in path doesn't exist, it won't be created. "t" is not needed as a default option.
=> FEATURE: Allow to save to file that doesn't exist

opcua/client/client.py, opcua/server/server.py, opcua/server/user_manager.py
When someone imports opcua, he/she sees 3 same warnings, even in
opcua is not used. I see the reasoning behind this feature, so I
propose to move it in classes. 
If you have another proposal, let me know, I can change the commit
=> FIX: Missing "cryptography" warning moved to class

opcua/client/client.py
I adjusted the string for die Client Signature Algorithm. As SHA1 is considered to be insecure, servers may reject encrypted connections when SHA1 is offered. Changing the algorithm to SHA256 seems to fix this issue.
=> Adjusting Client Signature Algorithm (FreeOpcUa/python-opcua#811)

opcua/server/history.py
Avoid the following exception by properly subclassing
history.SubHandler.
ERROR:opcua.common.subscription:Exception calling status change handler
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/opcua/common/subscription.py", line 180, in _call_status
self._handler.status_change_notification(status.Status)
AttributeError: 'SubHandler' object has no attribute 'status_change_notification'
=> Avoid exception in history subscription handler

examples/server-custom-object.py
added:
```
var = mycustomobj_type.add_variable(0, "var_should_be_there_after_instantiate", 1.0) # demonstrates instantiate
var.set_modelling_rule(True)
```
=> instantiate custom object type (server-custom-object.py) #1021

opcua/client/client.py
Previously we would have just raised an exception in case of
a session activiation failure (for example wrong password) but
the keepalive thread was kept running.
This change makes sure that all setup is torn down again in case
of a failure within "connect".
Hence, the library user can call connect() again if the previous
connect failed without having to explicitly clean up the half-baked
connect by calling disconnect.
=> Properly remove keepalive thread if session activation fails

opcua/common/subscription.py
import Iterable from collections.abc if python >= 3.6
=> remove DeprecationWarning

opcua/common/instantiate.py
Previously, the flag in which the user specified whether or not to
instantiate optional children was only honored on the top-level object
(i.e., first recursion round)
Fixes #1087
=> Honor option to instantiate optional children

opcua/common/instantiate.py
`instantiate` with `instantiate_optional=False` would also instantiate
children that have the ModellingRule OptionalPlaceholder. So far, only
Optional children were ignored.
This commit fixes this behavior, and treats both of them the same w.r.t.
`instantiate_optional`.
Fixes #1092
=> Also treat OptionalPlaceholder ModellingRule as optional in `instantiate`

opcua/server/address_space.py
I just spent a long time on a bug, and this small patch helped me narrow down the problem much more easily.
This adds a warning to the server logs when a read/write to an undefined attribute happens.
=> Write to the logs on invalid attribute read/write

opcua/server/address_space.py, tests/tests_common.py
Iterating over the references list and deleting inside the same list
resulted in dangling inverse references if nodes where deleted.
Fix this by iterating over a copy of the references list.
=> Make sure all inverse references are removed on node deletion

opcua/server/internal_server.py, opcua/server/server.py
Removes the need to patch in the Server object via the _parent attribute
in InternalServer if the InternalServer is instantiated outside of
Server.__init__.
Before this commit, the Server object passed itself into the
InternalServer constructor. If we instantiate an InternalServer (that we
want to pass in) before the Server, we obviously don't have a Server
instance to pass in as the parent. So we end up having to do this:
>>> my_iserver = CustomInternalServer()
>>> server = Server(iserver = my_iserver)
>>> server.iserver._parent = server # <-- no longer necessary
To preserve compatibility and keep changes to a minimum, a user_manager
property and setter are added to the Server class which redirect to the
user_manager attribute of the internal server.
=> Move user_manager from Server into InternalServer

opcua/server/internal_server.py
The _set_current_time() in the internal_server.py only updates the current time on the node (i=2258 [Server_ServerStatus_CurrentTime], the one on the node (i=2256 [Server_ServerStatus]) was omitted. This PR add its updating to the _set_current_time() method too.
=> Updating ServerStatus CurrentTime

opcua/server/server.py
The NodeId of the Server node has the identifier 2253, which does not
fit in the range (0 < id < 255) required by the two byte NodeId encoding
(OPC-6 5.2.2.9). Use FourByteNodeId instead.
Client side is correct since 2cbd3339.
=> Fix get_server_node in Server

opcua/common/events.py
Clients registering for multiple event types will usually construct a
select clause selecting _all_ fields of all subscribed events. For
example when subscribing for all events in server-events.py with
UaExport causes a ~200 field select clause.
When triggering an event we walk all requested fields in the select
clause (even though the event being triggered right now only has a few
of them).
In the server-events.py example this behavior causes quite some
overhead as from the ~200 requested fields only a few need to be
populated. For all other items a Variant(None) is instantiated.
Instead of instantiating a new Variant(None) for every none-existant
field we can just reuse the same instance for all none existant fields.
In my tests this caused a speed up >50% (~5ms -> ~2ms) for triggering …
=> Reuse the same Variant(None) on emitting events for non-existant fields

setup.py
This issue was first discovered when trying to install `opcua` using [poetry](https://python-poetry.org/).
This can be reproduced using the following
```sh
mkvirtualenv foo --python 3.7
pip install poetry
poetry init
poetry add opcua
```
where the following error is encountered
```sh
Package operations: 8 installs, 0 updates, 0 removals
• Installing futures (3.1.1)
• Installing six (1.15.0)
• Installing enum34 (1.1.10)
• Installing lxml (4.6.2)
• Installing python-dateutil (2.8.1)
• Installing pytz (2021.1)
• Installing trollius (2.2): Failed
RuntimeError
Unable to find installation candidates for trollius (2.2)
at ~/.virtual_envs/foo/lib/python3.7/site-packages/poetry/installation/chooser.py:73 in choose_for
69│             links.append(link)
70│ 
71│         if not links:
72│ …
```
=> Use environment markers for install dependencies

opcua/common/structures.py
Clean up invalid variable names in auto generation of Enums.
I encountered servers which have white spaces in enum types and invalid characters in enum values.
=> Also clean names for generated Enums

opcua/server/internal_server.py, opcua/server/server.py, tests/tests_crypto_connect.py
prevents unsupported identity tokens to create a session.
For example reject anonymous connection if not set via set_security_IDs, currently this was possible and was a security issue.
Fixes #1457
=> reject not supported identity tokens

opcua/ua/uatypes.py
If locale is set to emtpy string, to not localize text.  Fixes display of names in opcua-client-gui.  Regression introduced in 6ce82545e6aa91d42105b2ae902e18b01ff028bb
=> ignore emtpy locale

opcua/server/history.py
I believe there is an off-by-one error in calculation of history continuation point.
Same as in https://github.com/FreeOpcUa/opcua-asyncio/pull/1131
For example, I have a var on server with history of values [0, 1, 2, 3, 4, 5].
When I read history of that variable in portions of maxlen=3 with the use of continuation point, I get: [0, 1, 2], [4, 5]. The value 3 is never returned.
With the fix I get: [0, 1, 2], [3, 4, 5] as expected.
=> Fix history continuation point calculation.

opcua/common/structures.py
When trying to **load_type_definitions**, the OPCUA types that begin with numbers, e.g. 1/15, 2D or 3D will result in a **SyntaxError: cannot assign to operator**, as follows:
```
<Definition Name="1:SomeEnumeration">
<Field SymbolicName="S2D" Name="2D" Value="0"/>
<Field SymbolicName="S3D" Name="3D" Value="1"/>
</Definition>
```
Reason for the change:
Some OPCUA servers use the Enum Value names starting with numbers instead of valid names.
Those servers also use a SymbolicName which is not used by python-opcua, but there is a workaround to clean the name with leading numbers by using **_clean_name**.
See 666c0f182d3a8fae3fdb7e8bd64d9fe534595175
**See error:**
> Traceback (most recent call last):
>   File "C:\Users\RHU\repos\test-framework\src\cli.py", line 127, in main
> …
=> Fixed load_type_definitions OPCUA types that begin with numbers
