FreeOpcUa/python-opcua

.gitignore
opcua/node.py

Extended Node.set_value() to receive ua.DataValue objects directly.

---

opcua/client.py

Python client could not connect to .Net OPC UA server.
Server returned BadUserAccessDenied error. Client should not use
hardcoded PolicyId values, it should read them from ServerEndpoints.

Set correct PolicyId in UserIdentityToken

---

opcua/__init__.py

Added new decorator to automatically convert from and to variants for method which are class members since other is not working with them.

Added decorator for class members

---

opcua/uatypes.py

this should solve #38.
Ints are tested and still converted correctly.

Correctly guess booleans

---

example-server-methods.py
example-server.py
opcua/address_space.py
opcua/node.py
opcua/uaprocessor.py
opcua/uaprotocol_hand.py

Debug of TranslateBrowsePathsToNodeIds service. Still should be checked if it's implemented according to specification. Details in #34 
Current creation of new Arguments in the example-server is not so nice. We should think about a way to avid method *_guess_uatype* and enter type directly.
Also node.create_method should be extended so user can define a description.
Also mymethod is crashing the UaExpert... Don't merge for now.

Showing paramters in UaExpert

---

opcua/internal_server.py
opcua/uaprocessor.py
opcua/utils.py

Just raise ServiceError(code) to send error code to client

Refactor server-side service faults

---

make_deb.sh
stdeb.cfg

Hi here is a script for generating a debian package file
Cedric

add script for generating debian package

---

opcua/binary_client.py
opcua/client.py
opcua/node.py
opcua/status_code.py
opcua/tools.py
opcua/uaprocessor.py
schemas/generate_model.py
schemas/generate_statuscode.py
setup.py
tools/uahistoryread

New `uahistoryread` tool. Now it only supports reading raw values, other modes will be added in future versions.
Also, fixed some typos.

More tools

---

opcua/client.py

In ActivateSession parameters, PolicyId must match the Id of needed
UserTokenPolicy of endpoint. Some servers ignore this Id, but some
(like OPC Foundation's .Net UA library) return an error if PolicyId is invalid.

Choose PolicyId from list of policies

---

opcua/uaprotocol_auto.py
opcua/uaprotocol_hand.py
opcua/uatypes.py
schemas/generate_protocol_python.py

Skip typo check if PYOPCUA_NO_TYPO_CHECK is defined in env

---

opcua/tools.py

I've broken command-line tools in previous commit.

Set default security policy

---

opcua/binary_client.py
opcua/binary_server_asyncio.py
opcua/uaprotocol_auto.py
opcua/utils.py
schemas/uaprotocol_auto_add.py

change Buffer.copy() to return a shadow copy of Buffer.
add Buffer.skip() to skip length of bytes

add shadow copy to Buffer

---

opcua/client.py
opcua/uacrypto.py

Checked on OPC Foundation .net UA server

Support client-side encrypted passwords

---

opcua/client/client.py
opcua/crypto/uacrypto.py
opcua/server/server.py
opcua/tools.py

Remove unneeded function uacrypto.x509_to_der() (equivalent to uacrypto.der_from_x509()).
Pretty-print server certificate in uadiscover.

Cleanup crypto

---

opcua/ua/uaprotocol_auto.py
opcua/ua/uatypes.py
schemas/uaprotocol_auto_add.py
tests/tests.py

Revert previously deleted ExtensionObject class and add tests for custom ExtensionObjects. This fixes issue #111.

Support custom ExtensionObjects

---

examples/example-client_deleting.py
examples/example-server.py
opcua/client/binary_client.py
opcua/client/client.py
opcua/common/node.py
opcua/common/subscription.py
opcua/server/address_space.py
opcua/server/internal_server.py
opcua/server/internal_subscription.py
opcua/server/uaprocessor.py
opcua/ua/uaprotocol_auto.py
schemas/generate_model.py

It is almost finished. There is not clear to me how to notify clients when subscribed node is deleted. As far as I understood, I have to use [trigger_statuschange function](https://github.com/FreeOpcUa/python-opcua/blob/master/opcua/server/internal_subscription.py#L185) but don't know how to access it from node... Any help welcome!

Server side deleting of nodes.

---

opcua/client/client.py
opcua/crypto/security_policies.py

Client analyzes SecurityPolicyURI from the endpoint description, and then encrypts password with respective asymmetric algorithm.
This should close issue #125.
Tested on .Net UA server.

Use correct password encryption algorithm in client

---

opcua/common/manage_nodes.py

This is to add no input and output arguments if they are not provided. In this way I manage to have the same "interface" for adding methods and other objects into OPC UA server.

Added flexibility by adding functions into server

---

opcua/client/client.py
opcua/crypto/security_policies.py

Support passwords with SecurityPolicy#None (plain text)

---

opcua/common/manage_nodes.py
opcua/common/utils.py
opcua/server/address_space.py
opcua/server/internal_subscription.py
opcua/ua/uatypes.py
tests/tests_common.py
tests/tests_unit.py

use null identifier to trigger generation of nodeid 

---

opcua/server/server.py

Allow using Server with the with statement:
```
server = Server()
with server as server:
```

Turn Server into a context manager

---

examples/server-events.py
opcua/common/event.py
opcua/common/manage_nodes.py
tests/tests_server.py

Fixing the staff commented in #161:
* Added reference to event type (reference type: GeneratesEvent)
* Added in example @oroulet's way for creating custom event types
* Updated tests
* Correct definition of nodes defining new types

Events fixing

---

examples/client-events.py
examples/server-events.py
examples/server-example.py

This update is regarding recent events implementation.

Example update and new client-events example

---

opcua/server/internal_subscription.py

I think now I got it. #175 #182

Fixing the Modify Monitored Item response in the server.

---

README.md
opcua/server/address_space.py
opcua/server/internal_server.py
opcua/server/server.py
opcua/server/standard_address_space/standard_address_space.py
tests/tests.py
tests/tests_server.py

Add lazy loading feature to public API

Lazyloading

---

examples/server-events-history.py
opcua/common/events.py
opcua/common/node.py
opcua/common/subscription.py
opcua/common/utils.py
opcua/server/history.py
opcua/tools.py
tests/tests_history.py
tests/tests_subscriptions.py

take event as arg not evfilter
return EventResult obj and not fields
update command line to read events

event history api tweak

---

opcua/ua/uaprotocol_auto.py
schemas/generate_protocol_python.py

Must be tested, might have side effects

default strings and ByteString to None

---

opcua/client/ua_client.py
opcua/common/subscription.py
opcua/server/address_space.py
opcua/server/internal_subscription.py

Hi, I added these functions to the Client side. I don't think that the Modify Monitored Item function are in a good format, but they work fine if we want to change one monitored item.

Modify Monitored Item function and Deadband Monitor in the client side

---

.gitignore
examples/server-events-history.py
opcua/common/events.py
opcua/common/node.py
opcua/common/subscription.py
opcua/server/history.py
opcua/server/history_sql.py
opcua/server/internal_server.py
tests/tests_server.py
tests/tests_subscriptions.py

must be tested with external servers
@zerox1212 I just added the small fixes I suggested earlier and it seems to fix everything. Have a look

accept subscription to event type list

---

opcua/client/client.py

changed `_encrypt_password()` so it returns `(data,uri)` as expected by `_add_user_auth()`. Fix for issue #219

changed _encrypt_password() so it returns (data,uri) 

---

examples/server-customobject.py
opcua/common/manage_nodes.py
tests/tests_common.py

#210 contained an error. Is now fixed and also added an test to verify it TestCommon.test_add_node_withtype.

Fix support providing objecttype, added test

---

opcua/common/manage_nodes.py
tests/tests_server.py

Add datatype to create_variable

---

examples/server-callback.py
opcua/common/callback.py
opcua/common/utils.py
opcua/server/internal_server.py
opcua/server/server.py

Add server Event for client Item subscription
Usage : 
`self.server.subscribe_server_event("create_monitored_items", self.create_monitored_items)
self.server.subscribe_server_event("modify_monitored_items", self.modify_monitored_items)
self.server.subscribe_server_event("delete_monitored_items", self.delete_monitored_items)`

Issue #226

---

opcua/common/xmlimporter.py
opcua/common/xmlparser.py
tests/custom_nodes.xml
tests/tests_server.py

value support for  ListOfLocalizedText will also add support loading enumeration types from xml.
But only enums with EnumStrings not EnumValues.

[xmlimporter] support for values with ListOfLocalizedText

---

examples/server-enum.py

If you want to try it out; doesn't work on the current master it requires fixes for
add_subtype - requires extra argument for NodeClass. see PR #231
add_variable - requires extra argument for datatype. see PR #235

Example custom enumerations

---

opcua/server/server.py

Add possibility to overide internal server.

Add possibility to overide internal server

---

opcua/common/xmlimporter.py
opcua/common/xmlparser.py
opcua/server/server.py
tests/tests_server.py
tests/tests_unit.py

Use namespaces in XML import

---

opcua/common/xmlimporter.py
opcua/ua/uaprotocol_auto.py
tests/custom_nodes.xml
tests/tests_server.py

[Server] Allow Methods to be imported via XML

---

opcua/common/instantiate.py
opcua/common/xmlparser.py

This PR enables the use of Methods and DataType nodes within the instantiate method.

Add instantiate support for data types and methods

---

opcua/common/instantiate.py
opcua/common/xmlparser.py

Instatiate support for more types - FIX

---

opcua/common/subscription.py

Should correct #265 making Source and Server timestamps available.

Timestamps for data change event handler (#265)

---

opcua/common/node.py
opcua/server/internal_server.py
opcua/ua/uatypes.py
tests/tests_server.py

a few bug fixes (only one of them was hidden by faulty tests, the others are not properly tested)

Fix event notifier bugs

---

opcua/common/manage_nodes.py
opcua/common/node.py
opcua/server/internal_server.py
opcua/ua/uatypes.py
tests/tests.py
tests/tests_server.py
tests/tests_unit.py

Depends on #262. Only the last two commits are for this pull request.
The changes can be seen here: https://github.com/georgschoelly/python-opcua/compare/fix_event_notifier_bugs...georgschoelly:improve_enums

Improve enums

---

opcua/common/subscription.py

add explanation about sending two publish requests

---

opcua/common/utils.py
opcua/common/xmlimporter.py
opcua/common/xmlparser.py
opcua/server/event_generator.py
opcua/server/history.py
opcua/server/history_sql.py
opcua/server/internal_server.py
opcua/server/internal_subscription.py
opcua/server/server.py
opcua/server/subscription_service.py
opcua/server/uaprocessor.py
opcua/ua/uaprotocol_hand.py
opcua/ua/uatypes.py

[Server] Import XML - Respect depency of nodes (ParentNodeId)

---

opcua/__init__.py
opcua/common/node.py

More clean construction then the current one.

Fix to avoid circular import, including remove of *args

---

opcua/client/client.py

I've implemented a class that mirrors the alarms of my opc ua server. This involves keeping open a client subscribed to some events. In case the connection gets interrupted, I can just delete all my state and re-connect.
However, for this to work I need a way to detect a connection interruption. There seem to be some more people interested in this: https://github.com/FreeOpcUa/python-opcua/issues/106 (connection loss), https://github.com/FreeOpcUa/python-opcua/issues/146 (automatic reconnect).
I've started an implementation (untested so far) and I would like some feedback. I realise that the KeepAlive thread is probably going away in a future version of python-opcua when you switch to asyncio. However, I feel we could implement it for 1.0 anyway because it's quite important functionality. …

code improvements

---

opcua/client/ua_client.py

#152 re-send publish request on timeout

---

opcua/client/ua_client.py

might still change depending on #255

ignore BadNoSubscription and BadSessionClosed

---

opcua/common/xmlexporter.py
opcua/common/xmlimporter.py

Related to: https://github.com/FreeOpcUa/opcua-modeler/issues/9
Work in Progress, please don't merge yet.

Fix more issues if re-exporting DI schema

---

opcua/client/client.py

replaced leftover pack_bytes with new Bytes.pack

---

opcua/client/client.py
opcua/client/ua_client.py
opcua/common/utils.py

Added a timeout to the socket connection that prevents the ``UASocketClient`` from hanging on  ``_receive`` in ``_run``.

Prevent the UASocketClient from hanging

---

opcua/common/xmlparser.py
tests/custom_nodesns.xml
tests/tests_xml.py

migrate browsename namespace when importing to correct index

---

opcua/common/xmlimporter.py

Added support for Double and Float value extensions in XML importer.

Added: Support for Double and Float types in XML.

---

opcua/common/subscription.py

like dicts, etc. Going for an EAFP-approach here.

Made subscribe handle most iterables

---

opcua/common/manage_nodes.py
opcua/server/server.py
opcua/ua/uatypes.py
tests/tests_server.py

@zerox1212 
This is an attempt to solve your issue. Can you try to describe the issue again?

default_values

---

opcua/common/ua_utils.py
opcua/common/xmlexporter.py
tests/tests_xml.py

fix export Enum and custom datatype variables

---

opcua/client/ua_client.py

Maybe this works better than #316 ...

Solution for hanging UASocketClient (#316)

---

opcua/common/ua_utils.py
opcua/server/server.py

This pull request automatically fixes all occurrences of the following issue:
Issue type: [Avoid mutable default arguments](https://www.quantifiedcode.com/app/issue_class/3P0qV6OB)
Issue details: [https://www.quantifiedcode.com/app/project/gh:FreeOpcUa:python-opcua?groups=code_patterns/%3A3P0qV6OB](https://www.quantifiedcode.com/app/project/gh:FreeOpcUa:python-opcua?groups=code_patterns/%3A3P0qV6OB)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

Fix "Avoid mutable default arguments" issue

---

opcua/ua/uaprotocol_auto.py
opcua/ua/uaprotocol_hand.py

Currently the default AccessLevel and UserAccessLevel of node is undefined (=0 ).
This pr sets default to CurrentRead.

set default access level of nodes to read

---

examples/server-events.py

The problem was the missing path and using None
for Int and Bool properties

Fix issue with running server-events.py example

---

opcua/server/uaprocessor.py

Fixes #395.
Don't know how to make a regression test for it (see #95 for more info). For now used an external client ,which uses the intermediate chunks, to test this item.

fix support for intermediate chunks

---

opcua/client/client.py

username and password extracted from server_url to seperat attributes

---

examples/server-custom-object.py

Make the example working again

Fix broken example server-custom-object

---

examples/server-events.py

Make the example working again. 
UaError Exception due string instead of LocalizedText.

Fixed UaError; string wasn't a LocalizedText

---

opcua/common/xmlimporter.py

The value was not str but unicode
Pierre

Fixed minor issue #424 EngeineeringUnits could not be parsed

---

opcua/common/ua_utils.py
tests/tests_common.py

See #426 about data_type_to_variant_type .

fix ua_utils.data_type_to_variant_type for enum types

---

schemas/generate_address_space.py

Fixed codegenerator due changes in the xmlparser

---

opcua/common/methods.py

Before the fix, calling the method using a QualifiedName object as argument was not working, moreover it made the server saturate the RAM on my PC.

Let the use call a method using a QualifiedName object.

---

opcua/client/client.py

create_subscription argument period is in milliseconds

fixed docu

---

examples/client_to_kepware.py

don't forget to unsubscribe handle for tag1
example:
`handle = sub.subscribe_data_change(tag1) # e.g. handle = 112`
`handle = sub.subscribe_data_change(tag2) # e.g. handle = 114`
`sub.unsubscribe(handle) # sub.unsubscribe(112) is missing`

improved examples

---

opcua/common/instantiate.py

Hi, 
I had a bug creating an instance of a Type I imported via XML. Some Nodes where of NodeClass DataType which would trigger the warning l70 then crash l 93 because the object returned was None. 
I hope that my fix is ok with the specification. 
Thx

Updated instanciate.py to handle DataType Nodes

---

opcua/server/address_space.py

See [issue 486](https://github.com/FreeOpcUa/python-opcua/issues/486).

Fixed browse issue when ReferenceTypeId not specified.

---

opcua/common/manage_nodes.py
opcua/common/node.py
opcua/common/xmlimporter.py
opcua/common/xmlparser.py
opcua/server/address_space.py
opcua/server/standard_address_space/standard_address_space.py
schemas/generate_address_space.py
tests/custom_nodes.xml
tests/tests_client.py
tests/tests_cmd_lines.py
tests/tests_common.py
tests/tests_crypto_connect.py
tests/tests_history.py
tests/tests_server.py

add test for generated address space (#508)
Prints all skipped references(currently 1370) and nodes (0).

Improved handling of references

---

opcua/ua/ua_binary.py

Fix tested for python 2.7.6
https://github.com/FreeOpcUa/python-opcua/issues/518

fixed slow unpacking to Primitive1 array

---

opcua/tools.py

Argument passed to print_history is a list instead of ua.HistoryData.

print_history checking for incorrect type

---

opcua/server/binary_server_asyncio.py

separation OPCUAProtocol and BinaryServer

refactoring

---

opcua/common/instantiate.py
opcua/common/node.py
opcua/common/xmlimporter.py
tests/tests_common.py

as implementation was too simple and sometimes wrong

instantiation of optional nodes as parameter, do not set modelling rule automatically 

---

opcua/client/client.py
opcua/server/server.py

Fix typo in URN

---

examples/server-example.py
opcua/server/server.py

A small change that makes choosing the type of encryption a bit more configurable. The biggest change is the introduction of the property _nosecurity_ whit default value of True to maintain compatability.

option to disable anonymous connections to server

---

opcua/client/client.py

Change default UserIdentityToken.PolicyId value to String

---

opcua/server/internal_subscription.py
opcua/server/uaprocessor.py

https://github.com/FreeOpcUa/python-opcua/issues/659
https://github.com/FreeOpcUa/python-opcua/issues/661

fix: dictionary changed size during iteration

---

opcua/server/server.py

https://github.com/FreeOpcUa/python-opcua/pull/638#pullrequestreview-141134784

removed duplicate set_loop(None)

---

opcua/server/server.py

removed unused code: get_client_to_discovery

---

opcua/client/ua_client.py

Fixes https://github.com/FreeOpcUa/python-opcua/issues/735

fix race condition in UASocketClient

---

opcua/client/ua_client.py

cfr. https://github.com/FreeOpcUa/python-opcua/issues/739
cfr. https://linux.die.net/man/2/shutdown

fix OSError: [Errno 107] Transport endpoint is not connected

---

opcua/client/ua_client.py

Cfr. https://github.com/FreeOpcUa/python-opcua/issues/737

fix: don't send unsubscribe request if SecureChannel is closed

---

opcua/server/internal_server.py
opcua/server/server.py

Certificate is only used at higher Server level, no need to store in InternalServer.
Probably also for private_key...

moved certificate variable from InternalServer to Server class

---

opcua/server/history_sql.py

Hi, 
a small typo from a creator. Thank you for work.

now dv returns corrent timestamps

---

opcua/ua/uatypes.py

See https://github.com/FreeOpcUa/python-opcua/issues/757

is_array flag is not set in Variant(value=otherVariant) init

---

opcua/client/client.py
opcua/client/ua_client.py
opcua/server/discovery_service.py
opcua/server/internal_server.py
opcua/server/registration_service.py
opcua/server/server.py
opcua/server/uaprocessor.py
tests/tests_server.py

See #733
Fixes multiple issues with current discovery/registration implementation.
Pulls code outside server/client.py classes into a separate entity.

opc-ua registration and discovery refactoring

---

opcua/client/ua_client.py

Add timeout to initial socket creation (fix #714)

---

opcua/common/xmlexporter.py
tests/tests_xml.py

Fixes #860
Author:    Harold Howe <hhowe29@gmail.com>

Modified XML exporter to handle nodes with a null description

---

.gitignore
opcua/server/user_manager.py

decode password on None

---

opcua/client/ua_client.py

cfr. https://github.com/FreeOpcUa/python-opcua/issues/905

Don't wait on close_session() when underlying socket is closed

---

opcua/client/client.py
opcua/client/ua_client.py
opcua/common/connection.py
opcua/crypto/security_policies.py
opcua/server/uaprocessor.py
opcua/ua/uaprotocol_hand.py

See reported issue #910 for details.

Corrected change of security token after channel renewal

---

opcua/server/server.py

This allows consumers of the library to set buildinformation.
Additionally this fixes buildinformation representation in individual
nodes (like ua.ObjectIds.Server_ServerStatus_BuildInfo_ProductUri).
Before the individual buildinfo nodes haven't been populated. Now,
they are kept in sync with the buildinfo struct.

Allow customizing buildinfo

---

opcua/common/subscription.py

https://github.com/FreeOpcUa/python-opcua/issues/927

fixes warning: importing the ABCs from 'collections' is deprecated

---

opcua/client/client.py

The default timeouts are one hour, which is too long in some situations.
For example when developing a frequently crashing client program, it is easy to reach the limit of the number of sessions allowed by the server. Configuring a shorter timeout works around this problem.

opcua.Client: make session timeout and secure channel timeout configrable

---

opcua/server/internal_subscription.py

fixes https://github.com/FreeOpcUa/python-opcua/issues/934

bugfix: _not_acknowledged_results has items of type ua.PublishResult

---

opcua/server/internal_subscription.py

variant is not ua.Variant, but ua.DataValue

cleanup: variant -> datavalue

---

opcua/common/node.py

Fixed read history return

---

opcua/ua/uatypes.py

fixes https://github.com/FreeOpcUa/python-opcua/issues/965

fixed aware datetime to winNT time format

---

examples/server-example.py
opcua/ua/uatypes.py
tests/tests_unit.py

Fix error with guid as NodeIdType. For more information see issue #972

Fix error with guid as NodeIdType

---

opcua/common/xmlexporter.py

Wrong namespace index with xml export

---

opcua/server/address_space.py

Otherwise _translate_browsepath_to_nodeid behaves incorrect in various
situations. For example if requesting a browse path translation for
['2:X', '2:X', '2:X'] it would have returned the first object instead of
the last one as inverse references haven't been treated properly.
Now we treat the inverse flag, the reference type and its subtypes when
translating a browse path.

Fix _find_element_in_node to cover all input arguments

---

opcua/ua/uaprotocol_hand.py

solving issue with Siemens OPC-UA server rejecting hello message with too large buffers

issue_1029

---

opcua/common/node.py

#1057:
def __str__(self):
return self.nodeid[self.nodeid.find("(")+1:self.nodeid.find(")")]
def __repr__(self):
return "Node({0})".format(self.nodeid)
"str(node)" => "ns=2;i=2" and if you call repr(node) => Node(NumericNodeId(ns=2;i=2))

changed Nodeclass  __str__ and __repr__ method

---

opcua/common/subscription.py

Add list handeling for unsubbing

---

opcua/common/subscription.py

Fix double listing like mentioned in #1096

Unsub list handle

---

opcua/server/internal_subscription.py

Under various situations data change events can be lost due to
insufficient locking.
Data change events will be notified by an aspace callback to
MonitoredItemService which enqueues the accotrding events for processing
by the subscription publishing loop.
From internal_subscription.py:
339     def _pop_triggered_datachanges(self, result):
340         if self._triggered_datachanges:
341             notif = ua.DataChangeNotification()
342             notif.MonitoredItems = [item for sublist in self._triggered_datachanges.values() for item in sublist]
-> if anything is added to _triggered_datachanges in a second thread it'll be lost, see enqueue_datachange_event below
343             self._triggered_datachanges = {}
344             self.logger.debug("sending datachanges notification with %s …

Fix locking around internal_subscription queues

---

opcua/common/xmlexporter.py
opcua/common/xmlimporter.py

Various fixes for the xml import and export functionality.

Xml import export fixes

---

opcua/server/history_sql.py

changes:
```python
def save_event(self, event):
with self._lock:
_c_sub = self._conn.cursor()
table = self._get_table_name(event.SourceNode) #Emitting node is not always the Source (event.SourceNode)
columns, placeholders, evtup = self._format_event(event) #from event_prop_dict
event_type = event.EventType  # useful for troubleshooting database
try:
_c_sub.execute(
'INSERT INTO "{tn}" ("_Id", "_Timestamp", "_EventTypeName", {co}) VALUES (NULL, "{ts}", "{et}", {pl})'
.format(tn=table, co=columns, ts=event.Time, et=event_type, pl=placeholders), evtup)
except sqlite3.Error as e:
self.logger.error('Historizing SQL Insert Error for events from %s: %s', event.SourceNode, e)
self._conn.commit()
period = self._datachanges_period[event.SourceNode]
if period:
date_limit = datetime.utcnow() - period …
```

Fix history_sql.py emitting node is not the source - sql error

---

opcua/common/connection.py
opcua/server/uaprocessor.py

Pull request for the fix proposed by Brubbel in issue https://github.com/FreeOpcUa/python-opcua/issues/926.
As far as I can tell it fixes the problem.

Simple fix suggested by brubbel.

---

opcua/ua/uatypes.py

fix missing arg in __init__ from localizedtext

---

opcua/server/event_generator.py

Found the small typo error while reading the code.

Update event_generator.py Typo Error

---

examples/client-example.py
opcua/ua/uatypes.py
tests/tests_common.py

The following is the original :
https://github.com/FreeOpcUa/opcua-asyncio/pull/50/commits/0529ec7efd7aee28bf3612fc5d1658f282032101

Parse string Guid NodeId as UUID (#1141)
